# Generated by Django 4.2.19 on 2025-02-09 05:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="bath_toilet",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (
                        "バス",
                        [
                            ("専用バス", "専用バス"),
                            ("共同バス", "共同バス"),
                            ("シャワーのみ", "シャワーのみ"),
                            ("追い焚き機能", "追い焚き機能"),
                            ("浴室乾燥機", "浴室乾燥機"),
                        ],
                    ),
                    (
                        "トイレ",
                        [("専用トイレ", "専用トイレ"), ("共同トイレ", "共同トイレ"), ("温水洗浄便座", "温水洗浄便座")],
                    ),
                    ("バス・トイレ", [("バス・トイレ別", "バス・トイレ別")]),
                    ("その他", [("洗面台独立", "洗面台独立"), ("脱衣所", "脱衣所")]),
                ],
                max_length=150,
                null=True,
                verbose_name="風呂トイレ情報",
            ),
        ),
    ]
