# Generated by Django 4.2.19 on 2025-02-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_enviroment_post_eqipment_post_kitchen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_BT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="バスルーム機能")),
            ],
        ),
        migrations.CreateModel(
            name="BathToilet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="バストイレ種類")),
            ],
        ),
        migrations.CreateModel(
            name="Conro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="コンロ種類")),
            ],
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="周辺環境情報")),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="設備情報")),
            ],
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="キッチン種類")),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="bath_toilet",
        ),
        migrations.RemoveField(
            model_name="post",
            name="enviroment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="eqipment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="kitchen",
        ),
        migrations.AddField(
            model_name="post",
            name="station",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="駅までの時間"
            ),
        ),
        migrations.CreateModel(
            name="Room_Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_bt",
                    models.ManyToManyField(
                        blank=True, to="app.add_bt", verbose_name="バストイレ追加機能"
                    ),
                ),
                (
                    "bathtoilet",
                    models.ManyToManyField(
                        blank=True, to="app.bathtoilet", verbose_name="バストイレ"
                    ),
                ),
                (
                    "conro",
                    models.ManyToManyField(
                        blank=True, to="app.conro", verbose_name="コンロ"
                    ),
                ),
                (
                    "eqipment",
                    models.ManyToManyField(
                        blank=True, to="app.equipment", verbose_name="設備"
                    ),
                ),
                (
                    "kitchen",
                    models.ManyToManyField(
                        blank=True, to="app.kitchen", verbose_name="キッチン"
                    ),
                ),
            ],
        ),
    ]
