# Generated by Django 4.2.19 on 2025-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_add_bt_bathtoilet_conro_environment_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConroNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="コンロ数")),
            ],
        ),
    ]
