# Generated by Django 4.2.19 on 2025-02-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_conronum"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_function",
            name="conro_num",
            field=models.ManyToManyField(
                blank=True, to="app.conronum", verbose_name="コンロ数"
            ),
        ),
    ]
