# Generated by Django 4.2.19 on 2025-02-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_room_function_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Room_Function",
            new_name="RoomFunction",
        ),
    ]
