# Generated by Django 4.2.19 on 2025-02-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_room_function_roomfunction"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="add_bt",
            field=models.ManyToManyField(
                blank=True, to="app.add_bt", verbose_name="バストイレ追加機能"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bathtoilet",
            field=models.ManyToManyField(
                blank=True, to="app.bathtoilet", verbose_name="バストイレ"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="conro",
            field=models.ManyToManyField(
                blank=True, to="app.conro", verbose_name="コンロ"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="conro_num",
            field=models.ManyToManyField(
                blank=True, to="app.conronum", verbose_name="コンロ数"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="eqipment",
            field=models.ManyToManyField(
                blank=True, to="app.equipment", verbose_name="設備"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="kitchen",
            field=models.ManyToManyField(
                blank=True, to="app.kitchen", verbose_name="キッチン"
            ),
        ),
        migrations.DeleteModel(
            name="RoomFunction",
        ),
    ]
