# Generated by Django 4.2.19 on 2025-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_post_add_bt_post_bathtoilet_post_conro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="predict_price",
            field=models.FloatField(default=1, verbose_name="予測価格"),
            preserve_default=False,
        ),
    ]
