# Generated by Django 4.2.19 on 2025-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_post_predict_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_price", models.PositiveIntegerField(verbose_name="何円以上")),
                ("max_price", models.PositiveIntegerField(verbose_name="何円以下")),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("北区", "北区"),
                            ("中央区", "中央区"),
                            ("渋谷区", "渋谷区"),
                            ("杉並区", "杉並区"),
                            ("葛飾区", "葛飾区"),
                            ("荒川区", "荒川区"),
                            ("練馬区", "練馬区"),
                            ("目黒区", "目黒区"),
                            ("文京区", "文京区"),
                            ("板橋区", "板橋区"),
                            ("大田区", "大田区"),
                            ("江戸川区", "江戸川区"),
                            ("港区", "港区"),
                            ("墨田区", "墨田区"),
                            ("新宿区", "新宿区"),
                            ("中野区", "中野区"),
                            ("豊島区", "豊島区"),
                            ("台東区", "台東区"),
                            ("足立区", "足立区"),
                            ("世田谷区", "世田谷区"),
                            ("江東区", "江東区"),
                            ("品川区", "品川区"),
                            ("千代田区", "千代田区"),
                        ],
                        default="北区",
                        max_length=10,
                        verbose_name="地区",
                    ),
                ),
                (
                    "floor_num",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="階数"
                    ),
                ),
                (
                    "all_floor_num",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="建物の階数"
                    ),
                ),
                (
                    "floor_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "１部屋",
                                [
                                    ("1K", "1K"),
                                    ("1R", "1R"),
                                    ("1DK", "1DK"),
                                    ("1LDK", "1LDK"),
                                    ("1K+S(納戸)", "1K+S(納戸)"),
                                    ("1LDK+S(納戸)", "1LDK+S(納戸)"),
                                    ("1DK+S(納戸)", "1DK+S(納戸)"),
                                    ("1LK+S(納戸)", "1LK+S(納戸)"),
                                ],
                            ),
                            (
                                "２部屋",
                                [
                                    ("2K", "2K"),
                                    ("2DK", "2DK"),
                                    ("2LDK", "2LDK"),
                                    ("2K+S(納戸)", "2K+S(納戸)"),
                                    ("2DK+S(納戸)", "2DK+S(納戸)"),
                                    ("2LDK+S(納戸)", "2LDK+S(納戸)"),
                                ],
                            ),
                            (
                                "３部屋",
                                [
                                    ("3K", "3K"),
                                    ("3DK", "3DK"),
                                    ("3LDK", "3LDK"),
                                    ("3K+S(納戸)", "3K+S(納戸)"),
                                    ("3DK+S(納戸)", "3DK+S(納戸)"),
                                    ("3LDK+S(納戸)", "3LDK+S(納戸)"),
                                ],
                            ),
                            (
                                "４部屋以上",
                                [
                                    ("4K", "4K"),
                                    ("4DK", "4DK"),
                                    ("4LDK", "4LDK"),
                                    ("4LDK+S(納戸)", "4LDK+S(納戸)"),
                                    ("5K", "5K"),
                                    ("5DK", "5DK"),
                                    ("5LDK", "5LDK"),
                                    ("5DK+S(納戸)", "5DK+S(納戸)"),
                                    ("5LDK+S(納戸)", "5LDK+S(納戸)"),
                                    ("6LDK", "6LDK"),
                                ],
                            ),
                        ],
                        max_length=30,
                        verbose_name="間取り",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RC（鉄筋コンクリート）", "RC（鉄筋コンクリート）"),
                            ("SRC（鉄骨鉄筋コンクリート）", "SRC（鉄骨鉄筋コンクリート）"),
                            (
                                "PC（プレキャスト・コンクリート（鉄筋コンクリート））",
                                "PC（プレキャスト・コンクリート（鉄筋コンクリート））",
                            ),
                            ("HPC（プレキャスト・コンクリート（重量鉄骨））", "HPC（プレキャスト・コンクリート（重量鉄骨））"),
                            ("ALC（軽量気泡コンクリート）", "ALC（軽量気泡コンクリート）"),
                            ("鉄骨造", "鉄骨造"),
                            ("軽量鉄骨", "軽量鉄骨"),
                            ("木造", "木造"),
                            ("その他", "その他"),
                            ("ブロック", "ブロック"),
                        ],
                        max_length=80,
                        verbose_name="建物構造",
                    ),
                ),
                (
                    "station",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="駅までの時間"
                    ),
                ),
                (
                    "sun",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="日当たり"
                    ),
                ),
                (
                    "add_bt",
                    models.ManyToManyField(
                        blank=True, to="app.add_bt", verbose_name="バストイレ追加機能"
                    ),
                ),
                (
                    "bathtoilet",
                    models.ManyToManyField(
                        blank=True, to="app.bathtoilet", verbose_name="バストイレ"
                    ),
                ),
                (
                    "conro",
                    models.ManyToManyField(
                        blank=True, to="app.conro", verbose_name="コンロ"
                    ),
                ),
                (
                    "conro_num",
                    models.ManyToManyField(
                        blank=True, to="app.conronum", verbose_name="コンロ数"
                    ),
                ),
                (
                    "eqipment",
                    models.ManyToManyField(
                        blank=True, to="app.equipment", verbose_name="設備"
                    ),
                ),
                (
                    "kitchen",
                    models.ManyToManyField(
                        blank=True, to="app.kitchen", verbose_name="キッチン"
                    ),
                ),
            ],
        ),
    ]
