# Generated by Django 4.2.19 on 2025-03-01 10:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_post_predict_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Environment",
        ),
        migrations.AddField(
            model_name="search",
            name="predict_price",
            field=models.FloatField(blank=True, null=True, verbose_name="予測価格"),
        ),
        migrations.RemoveField(
            model_name="post",
            name="add_bt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="bathtoilet",
        ),
        migrations.RemoveField(
            model_name="post",
            name="conro",
        ),
        migrations.RemoveField(
            model_name="post",
            name="conro_num",
        ),
        migrations.RemoveField(
            model_name="post",
            name="eqipment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="kitchen",
        ),
        migrations.RemoveField(
            model_name="search",
            name="add_bt",
        ),
        migrations.RemoveField(
            model_name="search",
            name="bathtoilet",
        ),
        migrations.RemoveField(
            model_name="search",
            name="conro",
        ),
        migrations.RemoveField(
            model_name="search",
            name="conro_num",
        ),
        migrations.RemoveField(
            model_name="search",
            name="eqipment",
        ),
        migrations.RemoveField(
            model_name="search",
            name="kitchen",
        ),
        migrations.DeleteModel(
            name="Add_BT",
        ),
        migrations.DeleteModel(
            name="BathToilet",
        ),
        migrations.DeleteModel(
            name="Conro",
        ),
        migrations.DeleteModel(
            name="ConroNum",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="Kitchen",
        ),
        migrations.AddField(
            model_name="post",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("洗面台独立", "洗面台独立"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                    ("追焚機能", "追焚機能"),
                ],
                max_length=27,
                verbose_name="バストイレ追加機能",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bathtoilet",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("トイレ", [("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")]),
                    (
                        "バス",
                        [
                            ("バスなし", "バスなし"),
                            ("専用バス", "専用バス"),
                            ("共同バス", "共同バス"),
                            ("シャワー", "シャワー"),
                        ],
                    ),
                    ("バストイレ別", [("バス・トイレ別", "バス・トイレ別")]),
                ],
                max_length=13,
                verbose_name="バストイレ",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="conro",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("IHコンロ", "IHコンロ"), ("ガスコンロ", "ガスコンロ"), ("電気コンロ", "電気コンロ")],
                max_length=17,
                verbose_name="コンロ",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="conro_num",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="コンロ数"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="eqipment",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (
                        "収納関連",
                        [
                            ("ウォークインクローゼット", "ウォークインクローゼット"),
                            ("シューズボックス", "シューズボックス"),
                            ("トランクルーム", "トランクルーム"),
                            ("床下収納", "床下収納"),
                        ],
                    ),
                    ("空調関連", [("エアコン付", "エアコン付"), ("床暖房", "床暖房")]),
                    ("バリアフリー", [("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")]),
                    ("快適性", [("フローリング", "フローリング"), ("防音室", "防音室")]),
                    ("建物特徴", [("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")]),
                    ("屋外スペース", [("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")]),
                    ("エネルギー関連", [("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")]),
                    ("ゴミ関連", [("敷地内ごみ置き場", "敷地内ごみ置き場")]),
                    ("水道関連", [("公営水道", "公営水道")]),
                ],
                max_length=50,
                verbose_name="設備",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("L字キッチン", "L字キッチン"),
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("システムキッチン", "システムキッチン"),
                    ("独立キッチン", "独立キッチン"),
                ],
                max_length=32,
                verbose_name="キッチン",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("洗面台独立", "洗面台独立"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                    ("追焚機能", "追焚機能"),
                ],
                max_length=27,
                verbose_name="バストイレ追加機能",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="bathtoilet",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("トイレ", [("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")]),
                    (
                        "バス",
                        [
                            ("バスなし", "バスなし"),
                            ("専用バス", "専用バス"),
                            ("共同バス", "共同バス"),
                            ("シャワー", "シャワー"),
                        ],
                    ),
                    ("バストイレ別", [("バス・トイレ別", "バス・トイレ別")]),
                ],
                max_length=13,
                verbose_name="バストイレ",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="conro",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("IHコンロ", "IHコンロ"), ("ガスコンロ", "ガスコンロ"), ("電気コンロ", "電気コンロ")],
                max_length=17,
                verbose_name="コンロ",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="conro_num",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="コンロ数"
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="eqipment",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (
                        "収納関連",
                        [
                            ("ウォークインクローゼット", "ウォークインクローゼット"),
                            ("シューズボックス", "シューズボックス"),
                            ("トランクルーム", "トランクルーム"),
                            ("床下収納", "床下収納"),
                        ],
                    ),
                    ("空調関連", [("エアコン付", "エアコン付"), ("床暖房", "床暖房")]),
                    ("バリアフリー", [("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")]),
                    ("快適性", [("フローリング", "フローリング"), ("防音室", "防音室")]),
                    ("建物特徴", [("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")]),
                    ("屋外スペース", [("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")]),
                    ("エネルギー関連", [("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")]),
                    ("ゴミ関連", [("敷地内ごみ置き場", "敷地内ごみ置き場")]),
                    ("水道関連", [("公営水道", "公営水道")]),
                ],
                max_length=50,
                verbose_name="設備",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("L字キッチン", "L字キッチン"),
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("システムキッチン", "システムキッチン"),
                    ("独立キッチン", "独立キッチン"),
                ],
                max_length=32,
                verbose_name="キッチン",
            ),
        ),
    ]
