# Generated by Django 4.2.19 on 2025-03-01 15:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_delete_environment_search_predict_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="eqipment",
        ),
        migrations.RemoveField(
            model_name="search",
            name="eqipment",
        ),
        migrations.RemoveField(
            model_name="search",
            name="predict_price",
        ),
        migrations.AddField(
            model_name="post",
            name="air_conditioning",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("エアコン付", "エアコン付"), ("床暖房", "床暖房")],
                max_length=9,
                verbose_name="空調",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")],
                max_length=13,
                verbose_name="バリアフリー",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")],
                max_length=11,
                verbose_name="建物特長",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("フローリング", "フローリング"), ("防音室", "防音室")],
                max_length=10,
                verbose_name="快適設備",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="energy",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                max_length=11,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="garbage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")],
                max_length=8,
                verbose_name="ゴミ捨て場",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="outdoor",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")],
                max_length=14,
                verbose_name="屋外設備",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                    ("床下収納", "床下収納"),
                ],
                max_length=26,
                verbose_name="収納",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="water_supply",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[("公営水道", "公営水道")], max_length=4, verbose_name="水道"
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="air_conditioning",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("エアコン付", "エアコン付"), ("床暖房", "床暖房")],
                max_length=9,
                verbose_name="空調",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")],
                max_length=13,
                verbose_name="バリアフリー",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")],
                max_length=11,
                verbose_name="建物特長",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("フローリング", "フローリング"), ("防音室", "防音室")],
                max_length=10,
                verbose_name="快適設備",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="energy",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                max_length=11,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="garbage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")],
                max_length=8,
                verbose_name="ゴミ捨て場",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="outdoor",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")],
                max_length=14,
                verbose_name="屋外設備",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                    ("床下収納", "床下収納"),
                ],
                max_length=26,
                verbose_name="収納",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="water_supply",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[("公営水道", "公営水道")], max_length=4, verbose_name="水道"
            ),
        ),
    ]
