# Generated by Django 4.2.19 on 2025-03-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_post_eqipment_remove_search_eqipment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bathtoilet",
        ),
        migrations.RemoveField(
            model_name="search",
            name="bathtoilet",
        ),
        migrations.AddField(
            model_name="post",
            name="bath",
            field=models.CharField(
                blank=True,
                choices=[
                    ("バスなし", "バスなし"),
                    ("専用バス", "専用バス"),
                    ("共同バス", "共同バス"),
                    ("シャワー", "シャワー"),
                ],
                max_length=100,
                verbose_name="バス",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bath_toilet",
            field=models.BooleanField(blank=True, default=True, verbose_name="風呂トイレ別"),
        ),
        migrations.AddField(
            model_name="post",
            name="toilet",
            field=models.CharField(
                blank=True,
                choices=[("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")],
                max_length=100,
                verbose_name="トイレ",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="bath",
            field=models.CharField(
                blank=True,
                choices=[
                    ("バスなし", "バスなし"),
                    ("専用バス", "専用バス"),
                    ("共同バス", "共同バス"),
                    ("シャワー", "シャワー"),
                ],
                max_length=100,
                verbose_name="バス",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="bath_toilet",
            field=models.BooleanField(blank=True, default=True, verbose_name="風呂トイレ別"),
        ),
        migrations.AddField(
            model_name="search",
            name="toilet",
            field=models.CharField(
                blank=True,
                choices=[("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")],
                max_length=100,
                verbose_name="トイレ",
            ),
        ),
    ]
