# Generated by Django 4.2.19 on 2025-03-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_post_bathtoilet_remove_search_bathtoilet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="const_year",
            field=models.PositiveIntegerField(
                blank=True, default=5, verbose_name="築年数"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="room_size",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="部屋の広さ"
            ),
        ),
    ]
