# Generated by Django 4.2.19 on 2025-03-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_post_const_year_post_room_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Search",
        ),
    ]
