# Generated by Django 4.2.19 on 2025-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_delete_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="bath_toilet",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="風呂トイレ別"
            ),
        ),
    ]
