# Generated by Django 4.2.19 on 2025-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_post_bath_toilet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RC（鉄筋コンクリート）", "RC（鉄筋コンクリート）"),
                    ("鉄骨造", "鉄骨造"),
                    ("木造", "木造"),
                    ("SRC（鉄骨鉄筋コンクリート）", "SRC（鉄骨鉄筋コンクリート）"),
                    ("軽量鉄骨", "軽量鉄骨"),
                    ("ALC（軽量気泡コンクリート）", "ALC（軽量気泡コンクリート）"),
                    ("その他", "その他"),
                    ("PC（プレキャスト・コンクリート（鉄筋コンクリート））", "PC（プレキャスト・コンクリート（鉄筋コンクリート））"),
                    ("HPC（プレキャスト・コンクリート（重量鉄骨））", "HPC（プレキャスト・コンクリート（重量鉄骨））"),
                    ("ブロック", "ブロック"),
                ],
                max_length=80,
                verbose_name="建物構造",
            ),
        ),
    ]
