# Generated by Django 4.2.19 on 2025-03-02 15:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_post_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("洗面台独立", "洗面台独立"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                    ("追焚機能", "追焚機能"),
                ],
                max_length=27,
                null=True,
                verbose_name="バストイレ追加機能",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="air_conditioning",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("エアコン付", "エアコン付"), ("床暖房", "床暖房")],
                max_length=9,
                null=True,
                verbose_name="空調",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("北区", "北区"),
                    ("中央区", "中央区"),
                    ("渋谷区", "渋谷区"),
                    ("杉並区", "杉並区"),
                    ("葛飾区", "葛飾区"),
                    ("荒川区", "荒川区"),
                    ("練馬区", "練馬区"),
                    ("目黒区", "目黒区"),
                    ("文京区", "文京区"),
                    ("板橋区", "板橋区"),
                    ("大田区", "大田区"),
                    ("江戸川区", "江戸川区"),
                    ("港区", "港区"),
                    ("墨田区", "墨田区"),
                    ("新宿区", "新宿区"),
                    ("中野区", "中野区"),
                    ("豊島区", "豊島区"),
                    ("台東区", "台東区"),
                    ("足立区", "足立区"),
                    ("世田谷区", "世田谷区"),
                    ("江東区", "江東区"),
                    ("品川区", "品川区"),
                    ("千代田区", "千代田区"),
                ],
                default="北区",
                max_length=10,
                null=True,
                verbose_name="地区",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")],
                max_length=13,
                null=True,
                verbose_name="バリアフリー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="bath",
            field=models.CharField(
                blank=True,
                choices=[
                    ("バスなし", "バスなし"),
                    ("専用バス", "専用バス"),
                    ("共同バス", "共同バス"),
                    ("シャワー", "シャワー"),
                ],
                max_length=100,
                null=True,
                verbose_name="バス",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")],
                max_length=11,
                null=True,
                verbose_name="建物特長",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("フローリング", "フローリング"), ("防音室", "防音室")],
                max_length=10,
                null=True,
                verbose_name="快適設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conro",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("IHコンロ", "IHコンロ"), ("ガスコンロ", "ガスコンロ"), ("電気コンロ", "電気コンロ")],
                max_length=17,
                null=True,
                verbose_name="コンロ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conro_num",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="コンロ数"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="const_year",
            field=models.PositiveIntegerField(
                blank=True, default=5, null=True, verbose_name="築年数"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="energy",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                max_length=11,
                null=True,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="floor_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "１部屋",
                        [
                            ("1K", "1K"),
                            ("1R", "1R"),
                            ("1DK", "1DK"),
                            ("1LDK", "1LDK"),
                            ("1K+S(納戸)", "1K+S(納戸)"),
                            ("1LDK+S(納戸)", "1LDK+S(納戸)"),
                            ("1DK+S(納戸)", "1DK+S(納戸)"),
                            ("1LK+S(納戸)", "1LK+S(納戸)"),
                        ],
                    ),
                    (
                        "２部屋",
                        [
                            ("2K", "2K"),
                            ("2DK", "2DK"),
                            ("2LDK", "2LDK"),
                            ("2K+S(納戸)", "2K+S(納戸)"),
                            ("2DK+S(納戸)", "2DK+S(納戸)"),
                            ("2LDK+S(納戸)", "2LDK+S(納戸)"),
                        ],
                    ),
                    (
                        "３部屋",
                        [
                            ("3K", "3K"),
                            ("3DK", "3DK"),
                            ("3LDK", "3LDK"),
                            ("3K+S(納戸)", "3K+S(納戸)"),
                            ("3DK+S(納戸)", "3DK+S(納戸)"),
                            ("3LDK+S(納戸)", "3LDK+S(納戸)"),
                        ],
                    ),
                    (
                        "４部屋以上",
                        [
                            ("4K", "4K"),
                            ("4DK", "4DK"),
                            ("4LDK", "4LDK"),
                            ("4LDK+S(納戸)", "4LDK+S(納戸)"),
                            ("5K", "5K"),
                            ("5DK", "5DK"),
                            ("5LDK", "5LDK"),
                            ("5DK+S(納戸)", "5DK+S(納戸)"),
                            ("5LDK+S(納戸)", "5LDK+S(納戸)"),
                            ("6LDK", "6LDK"),
                        ],
                    ),
                ],
                max_length=30,
                null=True,
                verbose_name="間取り",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="garbage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")],
                max_length=8,
                null=True,
                verbose_name="ゴミ捨て場",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("L字キッチン", "L字キッチン"),
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("システムキッチン", "システムキッチン"),
                    ("独立キッチン", "独立キッチン"),
                ],
                max_length=32,
                null=True,
                verbose_name="キッチン",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="outdoor",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")],
                max_length=14,
                null=True,
                verbose_name="屋外設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="room_size",
            field=models.PositiveIntegerField(
                blank=True, default=10, null=True, verbose_name="部屋の広さ"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="station",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="駅までの時間"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                    ("床下収納", "床下収納"),
                ],
                max_length=26,
                null=True,
                verbose_name="収納",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RC（鉄筋コンクリート）", "RC（鉄筋コンクリート）"),
                    ("鉄骨造", "鉄骨造"),
                    ("木造", "木造"),
                    ("SRC（鉄骨鉄筋コンクリート）", "SRC（鉄骨鉄筋コンクリート）"),
                    ("軽量鉄骨", "軽量鉄骨"),
                    ("ALC（軽量気泡コンクリート）", "ALC（軽量気泡コンクリート）"),
                    ("その他", "その他"),
                    ("PC（プレキャスト・コンクリート（鉄筋コンクリート））", "PC（プレキャスト・コンクリート（鉄筋コンクリート））"),
                    ("HPC（プレキャスト・コンクリート（重量鉄骨））", "HPC（プレキャスト・コンクリート（重量鉄骨））"),
                    ("ブロック", "ブロック"),
                ],
                max_length=80,
                null=True,
                verbose_name="建物構造",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="toilet",
            field=models.CharField(
                blank=True,
                choices=[("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")],
                max_length=100,
                null=True,
                verbose_name="トイレ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="water_supply",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("公営水道", "公営水道")],
                max_length=4,
                null=True,
                verbose_name="水道",
            ),
        ),
    ]
