# Generated by Django 4.2.19 on 2025-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_post_add_bt_alter_post_air_conditioning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="area",
            field=models.CharField(
                choices=[
                    ("北区", "北区"),
                    ("中央区", "中央区"),
                    ("渋谷区", "渋谷区"),
                    ("杉並区", "杉並区"),
                    ("葛飾区", "葛飾区"),
                    ("荒川区", "荒川区"),
                    ("練馬区", "練馬区"),
                    ("目黒区", "目黒区"),
                    ("文京区", "文京区"),
                    ("板橋区", "板橋区"),
                    ("大田区", "大田区"),
                    ("江戸川区", "江戸川区"),
                    ("港区", "港区"),
                    ("墨田区", "墨田区"),
                    ("新宿区", "新宿区"),
                    ("中野区", "中野区"),
                    ("豊島区", "豊島区"),
                    ("台東区", "台東区"),
                    ("足立区", "足立区"),
                    ("世田谷区", "世田谷区"),
                    ("江東区", "江東区"),
                    ("品川区", "品川区"),
                    ("千代田区", "千代田区"),
                ],
                default="北区",
                max_length=10,
                verbose_name="地区",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="const_year",
            field=models.PositiveIntegerField(default=5, verbose_name="築年数"),
        ),
        migrations.AlterField(
            model_name="post",
            name="floor_plan",
            field=models.CharField(
                choices=[
                    (
                        "１部屋",
                        [
                            ("1K", "1K"),
                            ("1R", "1R"),
                            ("1DK", "1DK"),
                            ("1LDK", "1LDK"),
                            ("1K+S(納戸)", "1K+S(納戸)"),
                            ("1LDK+S(納戸)", "1LDK+S(納戸)"),
                            ("1DK+S(納戸)", "1DK+S(納戸)"),
                            ("1LK+S(納戸)", "1LK+S(納戸)"),
                        ],
                    ),
                    (
                        "２部屋",
                        [
                            ("2K", "2K"),
                            ("2DK", "2DK"),
                            ("2LDK", "2LDK"),
                            ("2K+S(納戸)", "2K+S(納戸)"),
                            ("2DK+S(納戸)", "2DK+S(納戸)"),
                            ("2LDK+S(納戸)", "2LDK+S(納戸)"),
                        ],
                    ),
                    (
                        "３部屋",
                        [
                            ("3K", "3K"),
                            ("3DK", "3DK"),
                            ("3LDK", "3LDK"),
                            ("3K+S(納戸)", "3K+S(納戸)"),
                            ("3DK+S(納戸)", "3DK+S(納戸)"),
                            ("3LDK+S(納戸)", "3LDK+S(納戸)"),
                        ],
                    ),
                    (
                        "４部屋以上",
                        [
                            ("4K", "4K"),
                            ("4DK", "4DK"),
                            ("4LDK", "4LDK"),
                            ("4LDK+S(納戸)", "4LDK+S(納戸)"),
                            ("5K", "5K"),
                            ("5DK", "5DK"),
                            ("5LDK", "5LDK"),
                            ("5DK+S(納戸)", "5DK+S(納戸)"),
                            ("5LDK+S(納戸)", "5LDK+S(納戸)"),
                            ("6LDK", "6LDK"),
                        ],
                    ),
                ],
                default=1,
                max_length=30,
                verbose_name="間取り",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="room_size",
            field=models.PositiveIntegerField(default=10, verbose_name="部屋の広さ"),
        ),
        migrations.AlterField(
            model_name="post",
            name="station",
            field=models.PositiveIntegerField(default=1, verbose_name="駅までの時間"),
        ),
        migrations.AlterField(
            model_name="post",
            name="structure",
            field=models.CharField(
                choices=[
                    ("RC（鉄筋コンクリート）", "RC（鉄筋コンクリート）"),
                    ("鉄骨造", "鉄骨造"),
                    ("木造", "木造"),
                    ("SRC（鉄骨鉄筋コンクリート）", "SRC（鉄骨鉄筋コンクリート）"),
                    ("軽量鉄骨", "軽量鉄骨"),
                    ("ALC（軽量気泡コンクリート）", "ALC（軽量気泡コンクリート）"),
                    ("その他", "その他"),
                    ("PC（プレキャスト・コンクリート（鉄筋コンクリート））", "PC（プレキャスト・コンクリート（鉄筋コンクリート））"),
                    ("HPC（プレキャスト・コンクリート（重量鉄骨））", "HPC（プレキャスト・コンクリート（重量鉄骨））"),
                    ("ブロック", "ブロック"),
                ],
                default=1,
                max_length=80,
                verbose_name="建物構造",
            ),
            preserve_default=False,
        ),
    ]
