# Generated by Django 4.2.19 on 2025-03-02 15:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_post_area_alter_post_const_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("洗面台独立", "洗面台独立"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                    ("追焚機能", "追焚機能"),
                ],
                default=[],
                max_length=27,
                verbose_name="バストイレ追加機能",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="air_conditioning",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("エアコン付", "エアコン付"), ("床暖房", "床暖房")],
                default=[],
                max_length=9,
                verbose_name="空調",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("バリアフリー", "バリアフリー"), ("エレベーター", "エレベーター")],
                default=[],
                max_length=13,
                verbose_name="バリアフリー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="bath",
            field=models.CharField(
                choices=[
                    ("バスなし", "バスなし"),
                    ("専用バス", "専用バス"),
                    ("共同バス", "共同バス"),
                    ("シャワー", "シャワー"),
                ],
                max_length=100,
                verbose_name="バス",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="bath_toilet",
            field=models.BooleanField(blank=True, default=True, verbose_name="風呂トイレ別"),
        ),
        migrations.AlterField(
            model_name="post",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("タイル張り", "タイル張り"), ("ロフト付き", "ロフト付き")],
                default=[],
                max_length=11,
                verbose_name="建物特長",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("フローリング", "フローリング"), ("防音室", "防音室")],
                default=[],
                max_length=10,
                verbose_name="快適設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conro",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("IHコンロ", "IHコンロ"), ("ガスコンロ", "ガスコンロ"), ("電気コンロ", "電気コンロ")],
                default=[],
                max_length=17,
                verbose_name="コンロ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conro_num",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="コンロ数"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="energy",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                default=[],
                max_length=11,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="garbage",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")],
                default=[],
                max_length=8,
                verbose_name="ゴミ捨て場",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("L字キッチン", "L字キッチン"),
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("システムキッチン", "システムキッチン"),
                    ("独立キッチン", "独立キッチン"),
                ],
                default=[],
                max_length=32,
                verbose_name="キッチン",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="outdoor",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")],
                default=[],
                max_length=14,
                verbose_name="屋外設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                    ("床下収納", "床下収納"),
                ],
                default=[],
                max_length=26,
                verbose_name="収納",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="toilet",
            field=models.CharField(
                choices=[("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")],
                max_length=100,
                verbose_name="トイレ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="water_supply",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("公営水道", "公営水道")], default=[], max_length=4, verbose_name="水道"
            ),
        ),
    ]
