# Generated by Django 4.2.19 on 2025-03-02 16:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_post_add_bt_alter_post_air_conditioning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("洗面台独立", "洗面台独立"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                ],
                default=[],
                max_length=22,
                verbose_name="バストイレ追加機能",
            ),
        ),
    ]
