# Generated by Django 4.2.19 on 2025-03-02 16:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_post_add_bt_alter_post_conro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("床下収納", "床下収納"),
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                ],
                default=[],
                max_length=26,
                verbose_name="収納",
            ),
        ),
    ]
