# Generated by Django 4.2.19 on 2025-03-02 16:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_post_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("エレベーター", "エレベーター"), ("バリアフリー", "バリアフリー")],
                default=[],
                max_length=13,
                verbose_name="バリアフリー",
            ),
        ),
    ]
