# Generated by Django 4.2.19 on 2025-03-02 17:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_post_barrier_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("ロフト付き", "ロフト付き"), ("タイル張り", "タイル張り")],
                default=[],
                max_length=11,
                verbose_name="建物特長",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="energy",
            field=models.CharField(
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                max_length=100,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="garbage",
            field=models.BooleanField(verbose_name="ゴミ捨て場"),
        ),
        migrations.AlterField(
            model_name="post",
            name="water_supply",
            field=models.BooleanField(
                choices=[("公営水道", "公営水道")], default=[], verbose_name="水道"
            ),
        ),
    ]
