# Generated by Django 4.2.19 on 2025-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_post_building_alter_post_energy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="garbage",
            field=models.CharField(
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")], max_length=100, verbose_name="ゴミ捨て場"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="water_supply",
            field=models.CharField(
                choices=[("公営水道", "公営水道")],
                default=[],
                max_length=100,
                verbose_name="水道",
            ),
        ),
    ]
