# Generated by Django 4.2.19 on 2025-03-03 04:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_post_garbage_alter_post_water_supply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="add_bt",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("追焚機能", "追焚機能"),
                    ("浴室乾燥機", "浴室乾燥機"),
                    ("温水洗浄便座", "温水洗浄便座"),
                    ("脱衣所", "脱衣所"),
                ],
                max_length=21,
                null=True,
                verbose_name="バストイレ追加機能",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="air_conditioning",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("エアコン付", "エアコン付"), ("床暖房", "床暖房")],
                max_length=9,
                null=True,
                verbose_name="空調",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="barrier_free",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("エレベーター", "エレベーター"), ("バリアフリー", "バリアフリー")],
                max_length=13,
                null=True,
                verbose_name="バリアフリー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="bath",
            field=models.CharField(
                blank=True,
                choices=[
                    ("バスなし", "バスなし"),
                    ("専用バス", "専用バス"),
                    ("共同バス", "共同バス"),
                    ("シャワー", "シャワー"),
                ],
                max_length=100,
                null=True,
                verbose_name="バス",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="building",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("ロフト付き", "ロフト付き"), ("タイル張り", "タイル張り")],
                max_length=11,
                null=True,
                verbose_name="建物特長",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comfort",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("フローリング", "フローリング"), ("防音室", "防音室")],
                max_length=10,
                null=True,
                verbose_name="快適設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conro",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("ガスコンロ", "ガスコンロ"), ("電気コンロ", "電気コンロ"), ("IHコンロ", "IHコンロ")],
                max_length=17,
                null=True,
                verbose_name="コンロ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="energy",
            field=models.CharField(
                blank=True,
                choices=[("都市ガス", "都市ガス"), ("プロパンガス", "プロパンガス")],
                max_length=100,
                null=True,
                verbose_name="エネルギー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="garbage",
            field=models.CharField(
                blank=True,
                choices=[("敷地内ごみ置き場", "敷地内ごみ置き場")],
                max_length=100,
                null=True,
                verbose_name="ゴミ捨て場",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("システムキッチン", "システムキッチン"),
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("独立キッチン", "独立キッチン"),
                    ("L字キッチン", "L字キッチン"),
                ],
                max_length=32,
                null=True,
                verbose_name="キッチン",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="outdoor",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("バルコニー", "バルコニー"), ("ルーフバルコニー", "ルーフバルコニー")],
                max_length=14,
                null=True,
                verbose_name="屋外設備",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="storage",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("床下収納", "床下収納"),
                    ("ウォークインクローゼット", "ウォークインクローゼット"),
                    ("シューズボックス", "シューズボックス"),
                ],
                max_length=26,
                null=True,
                verbose_name="収納",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="toilet",
            field=models.CharField(
                blank=True,
                choices=[("共同トイレ", "共同トイレ"), ("専用トイレ", "専用トイレ")],
                max_length=100,
                null=True,
                verbose_name="トイレ",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="water_supply",
            field=models.CharField(
                blank=True,
                choices=[("公営水道", "公営水道")],
                max_length=100,
                null=True,
                verbose_name="水道",
            ),
        ),
    ]
