# Generated by Django 4.2.19 on 2025-03-03 06:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_alter_post_add_bt_alter_post_air_conditioning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("カウンターキッチン", "カウンターキッチン"),
                    ("システムキッチン", "システムキッチン"),
                    ("独立キッチン", "独立キッチン"),
                    ("L字キッチン", "L字キッチン"),
                ],
                max_length=32,
                null=True,
                verbose_name="キッチン",
            ),
        ),
    ]
